// Column maps Form pembiayaan - auto-generated dari core/pembiayaan.py

export const MURABAHAH_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 17, "Tanggal Mulai": 21, "Tanggal Jatuh Tempo": 22, "Metode Sumber Dana": 23, "Porsi (%)": 24, "Lokasi Penggunaan": 25, "Jenis Piutang": 26, "Sifat Piutang": 27, "Status Piutang": 28, "Jenis Penggunaan": 29, "Sektor Ekonomi": 30, "Plafon": 31, "Periode Pembayaran": 32, "Imbalan Awal Kontrak (%)": 33, "Imbalan Bulan Laporan (%)": 34, "Kualitas": 35, "Status BMPD": 36, "Baki Debet": 37, "Biaya Adm Belum Diamortisasi": 38, "Saldo Margin Ditangguhkan": 40, "Jumlah": 41, "Tunggakan Hari": 42, "Tunggakan Pokok": 43, "Tunggakan Margin": 44, "Imbalan Akan Diterima": 45, "Jenis Agunan": 46, "Jenis Pengikatan": 47, "Kode/No Agunan": 48, "Karat": 49, "Berat": 50, "Latitude": 51, "Longitude": 52, "Golongan Penjamin": 53, "Tgl Penilaian Terakhir": 54, "Nilai Agunan": 55, "Nilai Dapat Diperhitungkan": 56, "Bagian Dijamin": 57, "CKPN": 58, "Jenis CKPN": 59, "Tgl Mulai Macet": 60, "Pembiayaan Program Pemerintah": 61, "Sektor KUR": 62, "Tgl Akad Awal": 63, "Tgl Akad Akhir": 64, "Sandi Fintech P2PL": 65};
export const MULTIJASA_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 18, "Tanggal Mulai": 21, "Tanggal Jatuh Tempo": 22, "Metode Sumber Dana": 23, "Porsi (%)": 24, "Lokasi Penggunaan": 25, "Jenis Piutang": 26, "Sifat Piutang": 27, "Status Piutang": 28, "Jenis Penggunaan": 29, "Sektor Ekonomi": 30, "Plafon": 31, "Periode Pembayaran": 32, "Imbalan Awal Kontrak (%)": 33, "Imbalan Bulan Laporan (%)": 34, "Kualitas": 35, "Status BMPD": 36, "Baki Debet": 39, "Biaya Adm Belum Diamortisasi": 38, "Saldo Margin Ditangguhkan": 40, "Jumlah": 41, "Tunggakan Hari": 42, "Tunggakan Pokok": 43, "Tunggakan Margin": 44, "Imbalan Akan Diterima": 45, "Jenis Agunan": 46, "Jenis Pengikatan": 47, "Kode/No Agunan": 48, "Karat": 49, "Berat": 50, "Latitude": 51, "Longitude": 52, "Golongan Penjamin": 53, "Tgl Penilaian Terakhir": 54, "Nilai Agunan": 55, "Nilai Dapat Diperhitungkan": 56, "Bagian Dijamin": 57, "CKPN": 58, "Jenis CKPN": 59, "Tgl Mulai Macet": 60, "Pembiayaan Program Pemerintah": 61, "Sektor KUR": 62, "Tgl Akad Awal": 63, "Tgl Akad Akhir": 64, "Sandi Fintech P2PL": 65};
export const ISTISHNA_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 18, "Tanggal Mulai": 21, "Tanggal Jatuh Tempo": 22, "Metode Sumber Dana": 23, "Porsi (%)": 24, "Lokasi Penggunaan": 25, "Jenis Piutang": 26, "Sifat Piutang": 27, "Status Piutang": 28, "Jenis Penggunaan": 29, "Sektor Ekonomi": 30, "Plafon": 31, "Periode Pembayaran": 32, "Imbalan Awal Kontrak (%)": 33, "Imbalan Bulan Laporan (%)": 34, "Kualitas": 35, "Status BMPD": 36, "Baki Debet": 39, "Biaya Adm Belum Diamortisasi": 38, "Saldo Margin Ditangguhkan": 40, "Jumlah": 41, "Tunggakan Hari": 42, "Tunggakan Pokok": 43, "Tunggakan Margin": 44, "Imbalan Akan Diterima": 45, "Jenis Agunan": 46, "Jenis Pengikatan": 47, "Kode/No Agunan": 48, "Karat": 49, "Berat": 50, "Latitude": 51, "Longitude": 52, "Golongan Penjamin": 53, "Tgl Penilaian Terakhir": 54, "Nilai Agunan": 55, "Nilai Dapat Diperhitungkan": 56, "Bagian Dijamin": 57, "CKPN": 58, "Jenis CKPN": 59, "Tgl Mulai Macet": 60, "Pembiayaan Program Pemerintah": 61, "Sektor KUR": 62, "Tgl Akad Awal": 63, "Tgl Akad Akhir": 64, "Sandi Fintech P2PL": 65};
export const QARDH_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 18, "Tanggal Mulai": 21, "Tanggal Jatuh Tempo": 22, "Metode Sumber Dana": 23, "Porsi (%)": 24, "Lokasi Penggunaan": 25, "Jenis Piutang": 26, "Sifat Piutang": 27, "Jenis Penggunaan": 28, "Status Piutang": 29, "Sektor Ekonomi": 30, "Plafon": 31, "Periode Pembayaran": 32, "Imbalan Awal Kontrak (%)": 33, "Imbalan Bulan Laporan (%)": 34, "Kualitas": 35, "Status BMPD": 36, "Baki Debet": 37, "Biaya Adm Belum Diamortisasi": 38, "Jumlah": 39, "Tunggakan Hari": 40, "Tunggakan Pokok": 41, "Tunggakan Margin": 42, "Imbalan Akan Diterima": 43, "Jenis Agunan": 44, "Jenis Pengikatan": 45, "Kode/No Agunan": 46, "Karat": 47, "Berat": 48, "Latitude": 49, "Longitude": 50, "Golongan Penjamin": 51, "Tgl Penilaian Terakhir": 52, "Nilai Agunan": 53, "Nilai Dapat Diperhitungkan": 54, "Bagian Dijamin": 55, "CKPN": 56, "Jenis CKPN": 57, "Tgl Mulai Macet": 58, "Pembiayaan Program Pemerintah": 59, "Sektor KUR": 60, "Tgl Akad Awal": 61, "Tgl Akad Akhir": 62, "Sandi Fintech P2PL": 63};
export const BAGI_HASIL_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 16, "Tanggal Mulai": 21, "Tanggal Jatuh Tempo": 22, "Metode Sumber Dana": 23, "Porsi (%)": 24, "Lokasi Penggunaan": 25, "Jenis Pembiayaan": 26, "Sifat Pembiayaan": 27, "Status Pembiayaan": 28, "Jenis Penggunaan": 29, "Sektor Ekonomi": 30, "Jenis Akad": 31, "Sifat Investasi": 32, "Metode Bagi Hasil": 33, "Nisbah (%)": 34, "Plafon": 35, "Periode Bayar Pokok": 36, "Periode Bayar BH": 37, "Imbalan Awal Kontrak (%)": 38, "Imbalan Bulan Laporan (%)": 39, "RBH/PBH (%)": 40, "Kualitas": 41, "Status BMPD": 42, "Baki Debet": 43, "Biaya Adm Belum Diamortisasi": 44, "Jumlah": 45, "Kelonggaran Tarik": 46, "Tunggakan Pokok Hari": 47, "Tunggakan Pokok Jumlah": 48, "Tunggakan BH Hari": 49, "Tunggakan BH Jumlah": 50, "Imbalan Akan Diterima": 51, "Jenis Agunan": 52, "Jenis Pengikatan": 53, "Kode/No Agunan": 54, "Karat": 55, "Berat": 56, "Latitude": 57, "Longitude": 58, "Golongan Penjamin": 59, "Tgl Penilaian Terakhir": 60, "Nilai Agunan": 61, "Nilai Dapat Diperhitungkan": 62, "Bagian Dijamin": 63, "CKPN": 64, "Jenis CKPN": 65, "Tgl Mulai Macet": 66, "Pembiayaan Program Pemerintah": 67, "Sektor KUR": 68, "Tgl Akad Awal": 69, "Tgl Akad Akhir": 70, "Sandi Fintech P2PL": 71};
export const IJARAH_COLS = {"ID Pihak Lawan": 3, "Nama Nasabah": 4, "Nomor Identitas": 5, "No Kelompok Nasabah": 10, "Golongan Nasabah": 11, "Hubungan dgn Bank": 13, "Kategori Usaha": 15, "Nomor Rekening": 16, "Tanggal Mulai": 18, "Tanggal Jatuh Tempo": 21, "Metode Sumber Dana": 22, "Porsi (%)": 23, "Lokasi Penggunaan": 24, "Jenis Pembiayaan": 25, "Sifat Pembiayaan": 26, "Status Pembiayaan": 27, "Jenis Penggunaan": 28, "Sektor Ekonomi": 29, "Jenis Akad": 30, "Jenis Aset": 31, "Waktu Perolehan": 32, "Plafon": 33, "_akum_penyusutan": 44, "Jumlah Periode Penyusutan": 34, "Metode Penyusutan": 35, "Periode Pembayaran Sewa": 36, "Baki Debet": null, "Imbalan Awal Kontrak (%)": 39, "Imbalan Bulan Laporan (%)": 40, "Kualitas": 41, "Status BMPD": 42, "Biaya Adm Belum Diamortisasi": 43, "Akum Penyusutan": 44, "Cadangan Penurunan Nilai": 45, "Tunggakan Hari": 46, "Tunggakan Pokok": 47, "Tunggakan Imbalan": 48, "Imbalan Akan Diterima": 49, "Jenis Agunan": 50, "Jenis Pengikatan": 51, "Kode/No Agunan": 52, "Karat": 53, "Berat": 54, "Latitude": 55, "Longitude": 56, "Golongan Penjamin": 57, "Tgl Penilaian Terakhir": 58, "Nilai Agunan": 59, "Nilai Dapat Diperhitungkan": 60, "Bagian Dijamin": 61, "CKPN": 62, "Jenis CKPN": 63, "Tgl Mulai Macet": 64, "Pembiayaan Program Pemerintah": 65, "Sektor KUR": 66, "Tgl Akad Awal": 67, "Tgl Akad Akhir": 68, "Sandi Fintech P2PL": 69};

export const FORMS = [
  ["KC0600", "Murabahah", MURABAHAH_COLS],
  ["KC0700", "Istishna", ISTISHNA_COLS],
  ["KC0800", "Multijasa", MULTIJASA_COLS],
  ["KC0900", "Qardh", QARDH_COLS],
  ["KC1000", "Bagi Hasil", BAGI_HASIL_COLS],
  ["KC1100", "Ijarah", IJARAH_COLS],
];

export const OUTPUT_COLS = ["Cabang", "Akad", "Flag Anomali", "Kol Label", "Hari Overdue", "Nama Nasabah", "Nomor Rekening", "Plafon", "Baki Debet", "Tunggakan Pokok", "Tunggakan Margin", "CKPN", "Nilai Agunan", "Nilai Dapat Diperhitungkan", "Kualitas", "Tanggal Mulai", "Tanggal Jatuh Tempo", "Tgl Mulai Macet", "Hubungan dgn Bank", "Jenis Penggunaan", "Lokasi Penggunaan", "Jenis Piutang", "Sektor Ekonomi", "Jenis Agunan", "Jenis Pengikatan", "Tgl Penilaian Terakhir", "Bagian Dijamin", "ID Pihak Lawan", "Nomor Identitas", "Status BMPD", "Sifat Piutang", "Imbalan Awal Kontrak (%)", "Imbalan Bulan Laporan (%)", "Saldo Margin Ditangguhkan", "Jumlah", "Imbalan Akan Diterima", "Tgl Akad Awal", "Tgl Akad Akhir", "File Sumber", "Baris Asli", "HT Flag", "NPF Flag", "Lama Macet (Hari)", "Keterangan Pengikatan"];
export const BH_EXTRA_COLS = ["Jenis Akad", "Nisbah (%)", "RBH/PBH (%)", "Tunggakan Pokok Hari", "Tunggakan Pokok Jumlah", "Tunggakan BH Hari", "Tunggakan BH Jumlah"];
export const IJR_EXTRA_COLS = ["Jenis Akad", "Jenis Aset", "Akum Penyusutan", "Tunggakan Imbalan"];
