// auto-generated dari core/penempatanData.py

export const SANDI_MAP_NAMES = {"Hubungan dgn Bank": "SANDI_HUBUNGAN_BANK", "Jenis Operasional": "SANDI_JENIS_OPERASIONAL", "Jenis Instrumen": "SANDI_JENIS_INSTRUMEN", "Metode Sumber Dana": "SANDI_SUMBER_DANA", "Jenis Akad": "SANDI_JENIS_AKAD", "Metode Bagi Hasil": "SANDI_METODE_BH", "Kualitas": "SANDI_KUALITAS", "Status BMPD": "SANDI_BMPD", "Jenis CKPN": "SANDI_JENIS_CKPN"};
export const SANDI_BMPD = {"00": "Tidak Melanggar", "11": "Melanggar Individu", "12": "Melanggar Kelompok", "13": "Melanggar Ind+Kel", "21": "Melampaui Individu", "22": "Melampaui Kelompok", "23": "Melampaui Ind+Kel"};
export const SANDI_HUBUNGAN_BANK = {"1": "Terkait", "2": "Tidak Terkait"};
export const SANDI_JENIS_AKAD = {"1": "Wadiah", "2": "Mudarabah", "9": "Lainnya"};
export const SANDI_JENIS_CKPN = {"1": "Individual", "2": "Kolektif", "3": "Aset Tidak Buruk", "4": "Aset Buruk"};
export const SANDI_JENIS_INSTRUMEN = {"1": "Giro", "3": "Tabungan Umum", "4": "Tab Khusus Lembaga Pengayom", "0": "Tab Khusus BPRS Lain-Likuiditas", "5": "Deposito Umum", "6": "Deposito Khusus Lembaga Pengayom", "8": "Deposito Khusus BPRS Lain-Likuiditas", "7": "Sertifikat Deposito Syariah", "2": "Penempatan Kerja Sama LPBBTI/Fintech P2PL", "9": "Lainnya"};
export const SANDI_JENIS_OPERASIONAL = {"1": "Syariah", "2": "Konvensional"};
export const SANDI_KUALITAS = {"1": "1-Lancar", "2": "2-DPK", "3": "3-KL", "4": "4-Diragukan", "5": "5-Macet"};
export const SANDI_MAP = {"Hubungan dgn Bank": {"1": "Terkait", "2": "Tidak Terkait"}, "Jenis Operasional": {"1": "Syariah", "2": "Konvensional"}, "Jenis Instrumen": {"1": "Giro", "3": "Tabungan Umum", "4": "Tab Khusus Lembaga Pengayom", "0": "Tab Khusus BPRS Lain-Likuiditas", "5": "Deposito Umum", "6": "Deposito Khusus Lembaga Pengayom", "8": "Deposito Khusus BPRS Lain-Likuiditas", "7": "Sertifikat Deposito Syariah", "2": "Penempatan Kerja Sama LPBBTI/Fintech P2PL", "9": "Lainnya"}, "Metode Sumber Dana": {"1": "Muthlaqah Profit Sharing", "2": "Muthlaqah Nonprofit Sharing", "3": "Muqayyadah Profit Sharing", "4": "Muqayyadah Nonprofit Sharing", "5": "SRIA"}, "Jenis Akad": {"1": "Wadiah", "2": "Mudarabah", "9": "Lainnya"}, "Metode Bagi Hasil": {"1": "Muthlaqah Profit Sharing", "2": "Muthlaqah Nonprofit Sharing", "3": "Muqayyadah Profit Sharing", "4": "Muqayyadah Nonprofit Sharing"}, "Kualitas": {"1": "1-Lancar", "2": "2-DPK", "3": "3-KL", "4": "4-Diragukan", "5": "5-Macet"}, "Status BMPD": {"00": "Tidak Melanggar", "11": "Melanggar Individu", "12": "Melanggar Kelompok", "13": "Melanggar Ind+Kel", "21": "Melampaui Individu", "22": "Melampaui Kelompok", "23": "Melampaui Ind+Kel"}, "Jenis CKPN": {"1": "Individual", "2": "Kolektif", "3": "Aset Tidak Buruk", "4": "Aset Buruk"}};
export const SANDI_METODE_BH = {"1": "Muthlaqah Profit Sharing", "2": "Muthlaqah Nonprofit Sharing", "3": "Muqayyadah Profit Sharing", "4": "Muqayyadah Nonprofit Sharing"};
export const SANDI_SUMBER_DANA = {"1": "Muthlaqah Profit Sharing", "2": "Muthlaqah Nonprofit Sharing", "3": "Muqayyadah Profit Sharing", "4": "Muqayyadah Nonprofit Sharing", "5": "SRIA"};
export const COL_MAP = {"ID Pihak Lawan": 3, "Sandi Bank": 4, "Nama Bank": 5, "Hubungan dgn Bank": 10, "Jenis Operasional": 11, "Jenis Instrumen": 13, "Tanggal Mulai": 15, "Tanggal Jatuh Tempo": 16, "Metode Sumber Dana": 18, "Porsi (%)": 21, "Jenis Akad": 22, "Metode Bagi Hasil": 23, "Nisbah (%)": 24, "Imbalan Awal Kontrak (%)": 25, "Imbalan Bulan Laporan (%)": 26, "Kualitas": 27, "Status BMPD": 28, "Jumlah": 29, "Nominal Diblokir": 30, "Alasan Diblokir": 31, "Imbalan Akan Diterima": 32, "CKPN": 33, "Jenis CKPN": 34};
export const OUTPUT_COLS = ["Cabang", "Nama Bank", "Sandi Bank", "ID Pihak Lawan", "Jenis Operasional", "Hubungan dgn Bank", "Jenis Instrumen", "Jenis Akad", "Tanggal Mulai", "Tanggal Jatuh Tempo", "Metode Sumber Dana", "Porsi (%)", "Metode Bagi Hasil", "Nisbah (%)", "Imbalan Awal Kontrak (%)", "Imbalan Bulan Laporan (%)", "Kualitas", "Status BMPD", "Jumlah", "Nominal Diblokir", "Alasan Diblokir", "Imbalan Akan Diterima", "CKPN", "Jenis CKPN", "Baris Asli"];
